name: Bug Report
description: Start a bug report.
title: "[BUG]: "
labels: ["Bug", "Unverified"]
body:
  - type: input
    id: commit-hash
    attributes:
      label: What is the bot's version?
      description: Please enter the current `commit` the bot is running on here (run `/version` to get all the details).
      placeholder: e.g. 97f0eff

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe what happened. Include as much detail as possible, screen shots if possible and steps to reproduce the issue.
      placeholder: Enter detailed description of the issue here
    validations:
      required: true

  - type: checkboxes
    id: parts-affected
    attributes:
      label: What parts of the bot were affected?
      description: Please select all the parts of the bot that were affected by the issue.
      options:
        - label: Commands
        - label: Permissions
        - label: Economy
        - label: Wolvesville
        - label: Town of Salem
        - label: None of these

  - type: input
    id: gamecode
    attributes:
      label: What was the game code of the game?
      description: Please enter the game code of the game here. Of course only if you were in a game when this bug occurred.
      placeholder: Enter gamecode here

  - type: input
    id: user-id
    attributes:
      label: Who reported this bug?
      description: "Please enter your user ID here. This is required to be able to assign the bug to you. [Can't find your user ID?](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-user-ID-)"
      placeholder: e.g. 517335997172809728
    validations:
      required: true
